version: 2
root-markers:
  - .git/
lint-debounce: 1s
tools:
  javascript-eslint: &javascript-eslint
    lint-command: './node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  typescript-prettier: &typescript-prettier
    format-command: './node_modules/.bin/prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser typescript --stdin-filepath ${INPUT}'
    format-stdin: true

  stylua: &stylua
    format-command: "stylua -g \"*.lua\" -g \"!*.spec.lua\" -- ."
    format-stdin: true

languages:
  typescript:
    - <<: *javascript-eslint
    - <<: *typescript-prettier

  lua:
    - <<: *stylua
