[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
hook_post_update = "TSUpdate"
on_event = "BufRead"

[[plugins]]
repo = "neovim/nvim-lspconfig"
on_event = "BufRead"

[[plugins]]
repo = "hrsh7th/nvim-cmp"
depends = ["hrsh7th/cmp-nvim-lsp"]
on_event = "InsertEnter"

[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"

[[plugins]]
repo = "nvim-lualine/lualine.nvim"
on_event = "VimEnter"

[[plugins]]
repo = "Shougo/dpp.vim"
on_path = "~/.cache/dpp/repos/github.com/Shougo/dpp.vim"

[[plugins]]
repo = "vim-denops/denops.vim"
on_event = "VimEnter"

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'

[[plugins]]
repo = "nvim-tree/nvim-tree.lua"
hook_add = '''
lua << EOF
require("nvim-tree").setup {}
EOF
'''
lazy = 0

[[plugins]]
repo = "nvim-tree/nvim-web-devicons"
lazy = 0

[[plugins]]
repo = "akinsho/bufferline.nvim"
depends = ["nvim-tree/nvim-web-devicons"]
